# Generated by Django 6.0.4 on 2026-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
